on:
  push:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./update
      - name: any changes?
        run: |
          git add .
          git diff --cached --exit-code
